server:
  port: 8081
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: iovu
    password: iovu
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#  social login : google kakao naver 이런식으로
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: j7UstD_wa5eX6DjumkIr
            client-secret: NruNE0JYIJ
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iovu.iovuback.domain